# Generated by Django 4.1.7 on 2023-04-09 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=50)),
                ('oficina', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=50)),
                ('contrasena', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('facultad', models.CharField(max_length=50)),
                ('docentes', models.ManyToManyField(to='tuProfe_app.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuProfe_app.docente')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuProfe_app.materia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuProfe_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general', models.PositiveIntegerField()),
                ('metodologia', models.PositiveIntegerField()),
                ('manejo_tema', models.PositiveIntegerField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuProfe_app.docente')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuProfe_app.materia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuProfe_app.usuario')),
            ],
        ),
    ]
