# Generated by Django 4.1.7 on 2023-06-14 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuProfe_app', '0003_alter_calificacion_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_estudiante', models.EmailField(max_length=50)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuProfe_app.docente')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuProfe_app.materia')),
            ],
        ),
    ]
